name: smiley_brooms
description: Smiley Brooms Cleaning Service App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version information
version: 2.0.0+21

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  skeletonizer: ^1.0.1
  animated_text_kit: ^4.2.2
  
  # Enhanced UI Libraries (NEW)
  flutter_markdown: ^0.6.18
  photo_view: ^0.14.0
  flutter_html: ^3.0.0-beta.2
  flutter_screenutil: ^5.9.0
  flutter_adaptive_scaffold: ^0.1.7+1
  expandable: ^5.0.1
  flutter_portal: ^1.1.4
  flutter_hooks: ^0.20.3
  flutter_layout_grid: ^2.0.5
  flutter_animate: ^4.5.0
  flutter_card_swiper: ^6.0.0
  flutter_advanced_switch: ^3.0.1
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Enhanced State Management (NEW)
  riverpod_annotation: ^2.3.3
  hooks_riverpod: ^2.4.9
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Navigation
  go_router: ^13.0.1
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  graphql_flutter: ^5.1.2
  
  # Enhanced Network Libraries (NEW)
  retrofit: ^4.0.3
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  dio_http2_adapter: ^2.3.1+1
  fresh_dio: ^0.4.1
  talker_dio_logger: ^2.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Enhanced Storage (NEW)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  
  # Authentication
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  firebase_remote_config: ^4.3.8
  
  # Payment
  flutter_stripe: ^10.0.0
  
  # Enhanced Payment (NEW)
  pay: ^1.1.2
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3
  logger: ^2.0.2+1
  sentry_flutter: ^7.14.0
  flutter_native_splash: ^2.3.10
  
  # Enhanced Utilities (NEW)
  talker: ^3.1.4
  flutter_loggy: ^2.0.2
  loggy: ^2.0.3
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  flutter_app_badger: ^1.5.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_displaymode: ^0.6.0
  flutter_timezone: ^1.0.8
  
  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Enhanced Maps & Location (NEW)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  mapbox_gl: ^0.16.0
  location: ^5.0.3
  
  # Content Presentation (NEW)
  flutter_widget_from_html: ^0.14.9
  flutter_math_fork: ^0.7.2
  flutter_tex: ^4.0.6
  flutter_quill: ^8.6.4
  video_player: ^2.8.1
  chewie: ^1.7.4
  better_player: ^0.0.83
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.1.47
  syncfusion_flutter_charts: ^24.1.47
  fl_chart: ^0.66.0
  
  # Accessibility & Internationalization (NEW)
  flutter_tts: ^3.8.5
  easy_localization: ^3.0.3
  flutter_gen: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.1
  
  # Enhanced Dev Dependencies (NEW)
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  drift_dev: ^2.14.1
  riverpod_generator: ^2.3.9
  flutter_gen_runner: ^5.3.2

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - assets/translations/
    - assets/html/
    - assets/markdown/
    - assets/pdf/
    - .env
  
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true
