export const ROOM_CONFIG = {
  roomPrices: {
    master_bedroom: 100,
    bedroom: 80,
    bathroom: 90,
    kitchen: 120,
    living_room: 110,
    dining_room: 70,
    office: 95,
    playroom: 85,
    mudroom: 60,
    laundry_room: 75,
    sunroom: 90,
    guest_room: 70,
    garage: 50,
  },
  frequencyMultipliers: {
    one_time: 1.0,
    weekly: 0.8, // 20% discount for weekly
    bi_weekly: 0.85, // 15% discount for bi-weekly
    monthly: 0.9, // 10% discount for monthly
    quarterly: 0.95, // 5% discount for quarterly
  },
  cleanlinessMultipliers: {
    1: 0.9, // Lightly dirty: 10% discount
    2: 0.95, // Moderately clean: 5% discount
    3: 1.0, // Standard: no change
    4: 1.05, // Quite dirty: 5% increase
    5: 1.1, // Very dirty: 10% increase
  },
  addOnPrices: {
    "oven-cleaning": 25,
    "fridge-cleaning": 20,
    "window-cleaning": 30,
    "laundry-service": 40,
  },
}

export const APP_CONSTANTS = {
  // General app constants
  APP_NAME: "Smiley Brooms",
  CONTACT_EMAIL: "support@smileybrooms.com",
  PHONE_NUMBER: "+1 (800) 555-0123",
  ADDRESS: "123 Clean Street, Sparkle City, CA 90210",
  // Feature flags (example)
  FEATURE_AI_CHATBOT: process.env.NEXT_PUBLIC_FEATURE_AI_POWERED_CHATBOT === "true",
  FEATURE_ADVANCED_CART: process.env.NEXT_PUBLIC_FEATURE_ADVANCED_CART === "true",
  FEATURE_ROOM_VISUALIZATION: process.env.NEXT_PUBLIC_FEATURE_ROOM_VISUALIZATION === "true",
  FEATURE_DYNAMIC_PAYMENT_OPTIONS: process.env.NEXT_PUBLIC_FEATURE_DYNAMIC_PAYMENT_OPTIONS === "true",
  FEATURE_ENHANCED_ACCESSIBILITY: process.env.NEXT_PUBLIC_FEATURE_ENHANCED_ACCESSIBILITY === "true",
  FEATURE_CAREER_APPLICATION: process.env.NEXT_PUBLIC_FEATURE_CAREER_APPLICATION === "true",
  FEATURE_EMAIL_SUMMARY: process.env.NEXT_PUBLIC_FEATURE_EMAIL_SUMMARY === "true",
  FEATURE_TERMS_AGREEMENT_POPUP: process.env.NEXT_PUBLIC_FEATURE_TERMS_AGREEMENT_POPUP === "true",
  FEATURE_DEVICE_OPTIMIZED_THEMES: process.env.NEXT_PUBLIC_FEATURE_DEVICE_OPTIMIZED_THEMES === "true",
  FEATURE_ADVANCED_SCROLL_PHYSICS: process.env.NEXT_PUBLIC_FEATURE_ADVANCED_SCROLL_PHYSICS === "true",
  FEATURE_GEOLOCATION_SERVICES: process.env.NEXT_PUBLIC_FEATURE_GEOLOCATION_SERVICES === "true",
  FEATURE_BIOMETRIC_AUTHENTICATION: process.env.NEXT_PUBLIC_FEATURE_BIOMETRIC_AUTHENTICATION === "true",
  FEATURE_WEB_SHARE_API: process.env.NEXT_PUBLIC_FEATURE_WEB_SHARE_API === "true",
  FEATURE_VOICE_COMMANDS: process.env.NEXT_PUBLIC_FEATURE_VOICE_COMMANDS === "true",
  FEATURE_PERFORMANCE_MONITORING: process.env.NEXT_PUBLIC_FEATURE_PERFORMANCE_MONITORING === "true",
  FEATURE_NETWORK_STATUS_INDICATOR: process.env.NEXT_PUBLIC_FEATURE_NETWORK_STATUS_INDICATOR === "true",
  FEATURE_BATTERY_STATUS_OPTIMIZATION: process.env.NEXT_PUBLIC_FEATURE_BATTERY_STATUS_OPTIMIZATION === "true",
  FEATURE_VIBRATION_FEEDBACK: process.env.NEXT_PUBLIC_FEATURE_VIBRATION_FEEDBACK === "true",
  FEATURE_KEYBOARD_SHORTCUTS: process.env.NEXT_PUBLIC_FEATURE_KEYBOARD_SHORTCUTS === "true",
  FEATURE_CLIPBOARD_INTEGRATION: process.env.NEXT_PUBLIC_FEATURE_CLIPBOARD_INTEGRATION === "true",
  FEATURE_DRAG_AND_DROP_SUPPORT: process.env.NEXT_PUBLIC_FEATURE_DRAG_AND_DROP_SUPPORT === "true",
  FEATURE_FULL_HOUSE_PACKAGES: process.env.NEXT_PUBLIC_FEATURE_FULL_HOUSE_PACKAGES === "true",
  FEATURE_CLEANLINESS_SLIDER: process.env.NEXT_PUBLIC_FEATURE_CLEANLINESS_SLIDER === "true",
  FEATURE_CUSTOM_QUOTE_WIZARD: process.env.NEXT_PUBLIC_FEATURE_CUSTOM_QUOTE_WIZARD === "true",
  FEATURE_SERVICE_COMPARISON_TABLE: process.env.NEXT_PUBLIC_FEATURE_SERVICE_COMPARISON_TABLE === "true",
  FEATURE_TESTIMONIALS_SECTION: process.env.NEXT_PUBLIC_FEATURE_TESTIMONIALS_SECTION === "true",
  FEATURE_FAQ_SECTION: process.env.NEXT_PUBLIC_FEATURE_FAQ_SECTION === "true",
  FEATURE_HOW_IT_WORKS_SECTION: process.env.NEXT_PUBLIC_FEATURE_HOW_IT_WORKS_SECTION === "true",
  FEATURE_CALL_TO_ACTION_SECTION: process.env.NEXT_PUBLIC_FEATURE_CALL_TO_ACTION_SECTION === "true",
  FEATURE_FLOATING_CART_BUTTON: process.env.NEXT_PUBLIC_FEATURE_FLOATING_CART_BUTTON === "true",
  FEATURE_ABANDONMENT_RESCUE: process.env.NEXT_PUBLIC_FEATURE_ABANDONMENT_RESCUE === "true",
  FEATURE_CART_HEALTH_DASHBOARD: process.env.NEXT_PUBLIC_FEATURE_CART_HEALTH_DASHBOARD === "true",
  FEATURE_PRODUCT_CATALOG: process.env.NEXT_PUBLIC_FEATURE_PRODUCT_CATALOG === "true",
  FEATURE_SERVICE_MAP: process.env.NEXT_PUBLIC_FEATURE_SERVICE_MAP === "true",
  FEATURE_CLEANING_CHECKLIST: process.env.NEXT_PUBLIC_FEATURE_CLEANING_CHECKLIST === "true",
  FEATURE_CLEANING_TEAM_SELECTOR: process.env.NEXT_PUBLIC_FEATURE_CLEANING_TEAM_SELECTOR === "true",
  FEATURE_CLEANING_TIME_ESTIMATOR: process.env.NEXT_PUBLIC_FEATURE_CLEANING_TIME_ESTIMATOR === "true",
  FEATURE_SERVICE_DETAILS_MODAL: process.env.NEXT_PUBLIC_FEATURE_SERVICE_DETAILS_MODAL === "true",
  FEATURE_SERVICE_TYPE_SELECTOR: process.env.NEXT_PUBLIC_FEATURE_SERVICE_TYPE_SELECTOR === "true",
  FEATURE_ROOM_CONFIGURATOR: process.env.NEXT_PUBLIC_FEATURE_ROOM_CONFIGURATOR === "true",
  FEATURE_MULTI_STEP_CUSTOMIZATION_WIZARD: process.env.NEXT_PUBLIC_FEATURE_MULTI_STEP_CUSTOMIZATION_WIZARD === "true",
  FEATURE_DYNAMIC_FORM_GENERATION: process.env.NEXT_PUBLIC_FEATURE_DYNAMIC_FORM_GENERATION === "true",
  FEATURE_CONDITIONAL_FIELDS: process.env.NEXT_PUBLIC_FEATURE_CONDITIONAL_FIELDS === "true",
  FEATURE_FORM_VALIDATION: process.env.NEXT_PUBLIC_FEATURE_FORM_VALIDATION === "true",
  FEATURE_MASKED_INPUTS: process.env.NEXT_PUBLIC_FEATURE_MASKED_INPUTS === "true",
  FEATURE_ERROR_BOUNDARY: process.env.NEXT_PUBLIC_FEATURE_ERROR_BOUNDARY === "true",
  FEATURE_COOKIE_CONSENT_MANAGER: process.env.NEXT_PUBLIC_FEATURE_COOKIE_CONSENT_MANAGER === "true",
  FEATURE_GDPR_COMPLIANCE: process.env.NEXT_PUBLIC_FEATURE_GDPR_COMPLIANCE === "true",
  FEATURE_TOS_GENERATOR: process.env.NEXT_PUBLIC_FEATURE_TOS_GENERATOR === "true",
  FEATURE_CSRF_PROTECTION: process.env.NEXT_PUBLIC_FEATURE_CSRF_PROTECTION === "true",
  FEATURE_RATE_LIMITING: process.env.NEXT_PUBLIC_FEATURE_RATE_LIMITING === "true",
  FEATURE_HONEYPOT_TRAPS: process.env.NEXT_PUBLIC_FEATURE_HONEYPOT_TRAPS === "true",
  FEATURE_ANALYTICS_DASHBOARD: process.env.NEXT_PUBLIC_FEATURE_ANALYTICS_DASHBOARD === "true",
  FEATURE_USER_BEHAVIOR_TRACKING: process.env.NEXT_PUBLIC_FEATURE_USER_BEHAVIOR_TRACKING === "true",
  FEATURE_CONVERSION_FUNNEL_TRACKING: process.env.NEXT_PUBLIC_FEATURE_CONVERSION_FUNNEL_TRACKING === "true",
  FEATURE_A_B_TESTING: process.env.NEXT_PUBLIC_FEATURE_A_B_TESTING === "true",
  FEATURE_HEATMAPS_AND_SESSION_REPLAY: process.env.NEXT_PUBLIC_FEATURE_HEATMAPS_AND_SESSION_REPLAY === "true",
  FEATURE_REALTIME_ANALYTICS: process.env.NEXT_PUBLIC_FEATURE_REALTIME_ANALYTICS === "true",
  FEATURE_CUSTOM_EVENTS: process.env.NEXT_PUBLIC_FEATURE_CUSTOM_EVENTS === "true",
  FEATURE_USER_SEGMENTATION: process.env.NEXT_PUBLIC_FEATURE_USER_SEGMENTATION === "true",
  FEATURE_PREDICTIVE_ANALYTICS: process.env.NEXT_PUBLIC_FEATURE_PREDICTIVE_ANALYTICS === "true",
  FEATURE_AI_DRIVEN_INSIGHTS: process.env.NEXT_PUBLIC_FEATURE_AI_DRIVEN_INSIGHTS === "true",
  FEATURE_DATA_EXPORT: process.env.NEXT_PUBLIC_FEATURE_DATA_EXPORT === "true",
  FEATURE_REPORT_GENERATION: process.env.NEXT_PUBLIC_FEATURE_REPORT_GENERATION === "true",
  FEATURE_DASHBOARD_CUSTOMIZATION: process.env.NEXT_PUBLIC_FEATURE_DASHBOARD_CUSTOMIZATION === "true",
  FEATURE_ALERT_NOTIFICATIONS: process.env.NEXT_PUBLIC_FEATURE_ALERT_NOTIFICATIONS === "true",
  FEATURE_INTEGRATION_WITH_CRM: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_CRM === "true",
  FEATURE_INTEGRATION_WITH_MARKETING_AUTOMATION:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_MARKETING_AUTOMATION === "true",
  FEATURE_INTEGRATION_WITH_HELP_DESK: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_HELP_DESK === "true",
  FEATURE_INTEGRATION_WITH_PAYMENT_GATEWAYS:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_PAYMENT_GATEWAYS === "true",
  FEATURE_INTEGRATION_WITH_ACCOUNTING_SOFTWARE:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_ACCOUNTING_SOFTWARE === "true",
  FEATURE_INTEGRATION_WITH_SCHEDULING_TOOLS:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_SCHEDULING_TOOLS === "true",
  FEATURE_INTEGRATION_WITH_COMMUNICATION_PLATFORMS:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_COMMUNICATION_PLATFORMS === "true",
  FEATURE_INTEGRATION_WITH_SOCIAL_MEDIA: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_SOCIAL_MEDIA === "true",
  FEATURE_INTEGRATION_WITH_CLOUD_STORAGE: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_CLOUD_STORAGE === "true",
  FEATURE_INTEGRATION_WITH_EMAIL_MARKETING: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_EMAIL_MARKETING === "true",
  FEATURE_INTEGRATION_WITH_SMS_GATEWAYS: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_SMS_GATEWAYS === "true",
  FEATURE_INTEGRATION_WITH_VOICE_APIS: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_VOICE_APIS === "true",
  FEATURE_INTEGRATION_WITH_MAP_APIS: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_MAP_APIS === "true",
  FEATURE_INTEGRATION_WITH_WEATHER_APIS: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_WEATHER_APIS === "true",
  FEATURE_INTEGRATION_WITH_CALENDAR_APIS: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_CALENDAR_APIS === "true",
  FEATURE_INTEGRATION_WITH_HR_SOFTWARE: process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_HR_SOFTWARE === "true",
  FEATURE_INTEGRATION_WITH_INVENTORY_MANAGEMENT:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_INVENTORY_MANAGEMENT === "true",
  FEATURE_INTEGRATION_WITH_PROJECT_MANAGEMENT:
    process.env.NEXT_PUBLIC_FEATURE_INTEGRATION_WITH_PROJECT_MANAGEMENT === "true",
}
