export const ROOM_CONFIG = {
  roomPrices: {
    master_bedroom: 50,
    bedroom: 40,
    bathroom: 30,
    kitchen: 60,
    living_room: 50,
    dining_room: 40,
    office: 40,
    playroom: 50,
    mudroom: 30,
    laundry_room: 30,
    sunroom: 40,
    guest_room: 30,
    garage: 60,
  },
  frequencyMultipliers: {
    one_time: 1,
    weekly: 0.8,
    biweekly: 0.9,
    monthly: 0.95,
    semi_annual: 5,
    annually: 9,
    vip_daily: 30,
  },
  serviceFee: 20,
}
