export const roomConfig = {
  serviceFee: 50,
  frequencyMultipliers: {
    one_time: 2.17,
    weekly: 1.0,
    biweekly: 1.2,
    monthly: 1.54,
    semi_annual: 1.92,
    annually: 2.56,
    vip_daily: 7.5,
  },
  roomTypes: [
    { id: "master_bedroom", name: "Master Bedroom" },
    { id: "bedroom", name: "Bedroom" },
    { id: "bathroom", name: "Bathroom" },
    { id: "kitchen", name: "Kitchen" },
    { id: "living_room", name: "Living Room" },
    { id: "dining_room", name: "Dining Room" },
    { id: "office", name: "Office" },
    { id: "playroom", name: "Playroom" },
    { id: "mudroom", name: "Mudroom" },
    { id: "laundry_room", name: "Laundry Room" },
    { id: "sunroom", name: "Sunroom" },
    { id: "guest_room", name: "Guest Room" },
    { id: "garage", name: "Garage" },
  ],
}
