// Define the room tiers, add-ons, and reductions for the room configurator

export interface RoomTier {
  id: string
  name: string
  description: string
  price: number
  features: string[]
  timeEstimate: string
  detailedTasks: string[] // New field for detailed task breakdown
  notIncludedTasks: string[] // New field for tasks not included
  upsellMessage?: string // New field for upselling
  guarantee?: string // New field for guarantee
}

export interface RoomAddOn {
  id: string
  name: string
  price: number
  description?: string
}

export interface RoomReduction {
  id: string
  name: string
  discount: number
  description?: string
}

// Updated tiers with detailed task breakdowns from the strategic analysis

export const defaultTiers: Record<string, RoomTier[]> = {
  bedroom: [
    {
      id: "bedroom-standard",
      name: "STANDARD",
      description: "Basic maintenance for lightly used rooms",
      price: 50.0,
      timeEstimate: "15-20 min",
      features: ["Vacuum floors", "Change bedsheets", "Dust surfaces"],
      detailedTasks: ["✓ Vacuum floors", "✓ Change bedsheets", "✓ Dust surfaces"],
      notIncludedTasks: [
        "✗ Under-bed cleaning",
        "✗ Wardrobe organization",
        "✗ Mirror polishing",
        "✗ Steam clean mattress",
        "✗ UV sanitize high-touch",
        "✗ Curtain vacuuming",
        "✗ Baseboard disinfection",
      ],
      upsellMessage:
        "For a deeper clean including under-bed areas and wardrobe organization, consider our PREMIUM tier.",
      guarantee: "7-day",
    },
    {
      id: "bedroom-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for health-conscious families",
      price: 150.0,
      timeEstimate: "45-60 min",
      features: ["Includes Standard tasks", "Under-bed cleaning", "Wardrobe organization", "Mirror polishing"],
      detailedTasks: [
        "✓ Vacuum floors",
        "✓ Change bedsheets",
        "✓ Dust surfaces",
        "✓ Under-bed cleaning",
        "✓ Wardrobe organization",
        "✓ Mirror polishing",
      ],
      notIncludedTasks: [
        "✗ Steam clean mattress",
        "✗ UV sanitize high-touch",
        "✗ Curtain vacuuming",
        "✗ Baseboard disinfection",
      ],
      upsellMessage:
        "Achieve maximum freshness with our ELITE tier, covering every detail from mattress to baseboards.",
      guarantee: "30-day",
    },
    {
      id: "bedroom-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for luxury homes/Airbnb Superhosts",
      price: 250.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Steam clean mattress",
        "UV sanitize high-touch",
        "Curtain vacuuming",
        "Baseboard disinfection",
      ],
      detailedTasks: [
        "✓ Vacuum floors",
        "✓ Change bedsheets",
        "✓ Dust surfaces",
        "✓ Under-bed cleaning",
        "✓ Wardrobe organization",
        "✓ Mirror polishing",
        "✓ Steam clean mattress",
        "✓ UV sanitize high-touch",
        "✓ Curtain vacuuming",
        "✓ Baseboard disinfection",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  bathroom: [
    {
      id: "bathroom-standard",
      name: "STANDARD",
      description: "Basic cleaning for guest bathrooms",
      price: 75.0,
      timeEstimate: "15-20 min",
      features: ["Toilet scrub", "Sink/disinfect", "Mirror clean"],
      detailedTasks: ["✓ Toilet scrub", "✓ Sink/disinfect", "✓ Mirror clean"],
      notIncludedTasks: [
        "✗ Grout steam cleaning",
        "✗ Shower door track cleaning",
        "✗ Fixture polishing",
        "✗ Full tile resealing",
        "✗ Drain sanitization",
        "✗ Ventilation duct wipe",
        "✗ Under-sink organization",
      ],
      upsellMessage: "For a deeper clean of your shower/tub and toilet, upgrade to our PREMIUM tier.",
      guarantee: "7-day",
    },
    {
      id: "bathroom-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for regular bathrooms",
      price: 225.0,
      timeEstimate: "45-60 min",
      features: ["Includes Standard tasks", "Grout steam cleaning", "Shower door track cleaning", "Fixture polishing"],
      detailedTasks: [
        "✓ Toilet scrub",
        "✓ Sink/disinfect",
        "✓ Mirror clean",
        "✓ Grout steam cleaning",
        "✓ Shower door track cleaning",
        "✓ Fixture polishing",
      ],
      notIncludedTasks: [
        "✗ Full tile resealing",
        "✗ Drain sanitization",
        "✗ Ventilation duct wipe",
        "✗ Under-sink organization",
      ],
      upsellMessage:
        "Experience the ultimate bathroom refresh with our ELITE tier, including full tile resealing and drain sanitization.",
      guarantee: "30-day",
    },
    {
      id: "bathroom-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for master bathrooms",
      price: 375.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Full tile resealing",
        "Drain sanitization",
        "Ventilation duct wipe",
        "Under-sink organization",
      ],
      detailedTasks: [
        "✓ Toilet scrub",
        "✓ Sink/disinfect",
        "✓ Mirror clean",
        "✓ Grout steam cleaning",
        "✓ Shower door track cleaning",
        "✓ Fixture polishing",
        "✓ Full tile resealing",
        "✓ Drain sanitization",
        "✓ Ventilation duct wipe",
        "✓ Under-sink organization",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  kitchen: [
    {
      id: "kitchen-standard",
      name: "STANDARD",
      description: "Surface cleaning for lightly used kitchens",
      price: 125.0,
      timeEstimate: "15-20 min",
      features: ["Countertop disinfect", "Stove wipe", "Floor mop"],
      detailedTasks: ["✓ Countertop disinfect", "✓ Stove wipe", "✓ Floor mop"],
      notIncludedTasks: [
        "✗ Backsplash degreasing",
        "✗ Appliance exterior polish",
        "✗ Cabinet front wipe",
        "✗ Oven interior (full)",
        "✗ Fridge interior (full)",
        "✗ Under-appliance pull-out",
        "✗ Coffee machine descale",
      ],
      upsellMessage:
        "For a more comprehensive kitchen clean, including backsplash degreasing and appliance exterior polish, choose our PREMIUM tier.",
      guarantee: "7-day",
    },
    {
      id: "kitchen-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for regular kitchens",
      price: 375.0,
      timeEstimate: "45-60 min",
      features: ["Includes Standard tasks", "Backsplash degreasing", "Appliance exterior polish", "Cabinet front wipe"],
      detailedTasks: [
        "✓ Countertop disinfect",
        "✓ Stove wipe",
        "✓ Floor mop",
        "✓ Backsplash degreasing",
        "✓ Appliance exterior polish",
        "✓ Cabinet front wipe",
      ],
      notIncludedTasks: [
        "✗ Oven interior (full)",
        "✗ Fridge interior (full)",
        "✗ Under-appliance pull-out",
        "✗ Coffee machine descale",
      ],
      upsellMessage:
        "For a truly spotless kitchen, our ELITE tier offers deep cleaning of your oven, refrigerator interior, and more!",
      guarantee: "30-day",
    },
    {
      id: "kitchen-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for gourmet kitchens",
      price: 625.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Oven interior (full)",
        "Fridge interior (full)",
        "Under-appliance pull-out",
        "Coffee machine descale",
      ],
      detailedTasks: [
        "✓ Countertop disinfect",
        "✓ Stove wipe",
        "✓ Floor mop",
        "✓ Backsplash degreasing",
        "✓ Appliance exterior polish",
        "✓ Cabinet front wipe",
        "✓ Oven interior (full)",
        "✓ Fridge interior (full)",
        "✓ Under-appliance pull-out",
        "✓ Coffee machine descale",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  livingRoom: [
    {
      id: "livingroom-standard",
      name: "STANDARD",
      description: "Basic cleaning for living spaces",
      price: 80.0,
      timeEstimate: "15-20 min",
      features: ["Surface dusting", "Floor vacuum", "Coffee table cleaning"],
      detailedTasks: ["✓ Surface dusting", "✓ Floor vacuum", "✓ Coffee table cleaning"],
      notIncludedTasks: [
        "✗ Furniture vacuuming",
        "✗ Under furniture cleaning",
        "✗ Baseboard dusting",
        "✗ Electronics dusting",
        "✗ Upholstery spot treatment",
        "✗ Ceiling fan detailed cleaning",
        "✗ Window sill detailing",
        "✗ Decor item individual cleaning",
      ],
      upsellMessage:
        "For a more thorough clean including furniture vacuuming and under-furniture areas, consider our PREMIUM tier.",
      guarantee: "7-day",
    },
    {
      id: "livingroom-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for family rooms",
      price: 240.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Furniture vacuuming",
        "Under furniture cleaning",
        "Baseboard dusting",
        "Electronics dusting",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor vacuum",
        "✓ Coffee table cleaning",
        "✓ Furniture vacuuming",
        "✓ Under furniture cleaning",
        "✓ Baseboard dusting",
        "✓ Electronics dusting",
      ],
      notIncludedTasks: [
        "✗ Upholstery spot treatment",
        "✗ Ceiling fan detailed cleaning",
        "✗ Window sill detailing",
        "✗ Decor item individual cleaning",
      ],
      upsellMessage:
        "For the ultimate living room transformation, our ELITE tier offers upholstery spot treatment, detailed ceiling fan cleaning, and more!",
      guarantee: "30-day",
    },
    {
      id: "livingroom-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for entertainment areas",
      price: 400.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Upholstery spot treatment",
        "Ceiling fan detailed cleaning",
        "Window sill detailing",
        "Decor item individual cleaning",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor vacuum",
        "✓ Coffee table cleaning",
        "✓ Furniture vacuuming",
        "✓ Under furniture cleaning",
        "✓ Baseboard dusting",
        "✓ Electronics dusting",
        "✓ Upholstery spot treatment",
        "✓ Ceiling fan detailed cleaning",
        "✓ Window sill detailing",
        "✓ Decor item individual cleaning",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  diningRoom: [
    {
      id: "diningroom-standard",
      name: "STANDARD",
      description: "Basic cleaning for dining areas",
      price: 70.0,
      timeEstimate: "15-20 min",
      features: ["Table and chair dusting", "Floor vacuum/sweep", "Light fixture dusting"],
      detailedTasks: ["✓ Table and chair dusting", "✓ Floor vacuum/sweep", "✓ Light fixture dusting"],
      notIncludedTasks: [
        "✗ Table polishing",
        "✗ Chair detailed cleaning",
        "✗ Baseboards dusting",
        "✗ China cabinet exterior cleaning",
        "✗ Floor detailed cleaning",
        "✗ China/glassware cleaning",
        "✗ Cabinet interior organization",
        "✗ Chandelier detailed cleaning",
      ],
      upsellMessage:
        "For a more polished dining experience, our PREMIUM tier includes table polishing and detailed chair cleaning.",
      guarantee: "7-day",
    },
    {
      id: "diningroom-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for dining rooms",
      price: 210.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Table polishing",
        "Chair detailed cleaning",
        "Baseboards dusting",
        "China cabinet exterior cleaning",
        "Floor detailed cleaning",
      ],
      detailedTasks: [
        "✓ Table and chair dusting",
        "✓ Floor vacuum/sweep",
        "✓ Light fixture dusting",
        "✓ Table polishing",
        "✓ Chair detailed cleaning",
        "✓ Baseboards dusting",
        "✓ China cabinet exterior cleaning",
        "✓ Floor detailed cleaning",
      ],
      notIncludedTasks: [
        "✗ China/glassware cleaning",
        "✗ Cabinet interior organization",
        "✗ Chandelier detailed cleaning",
      ],
      upsellMessage:
        "Transform your dining room into a sparkling haven with our ELITE tier, featuring chandelier cleaning and fine china care!",
      guarantee: "30-day",
    },
    {
      id: "diningroom-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for formal dining rooms",
      price: 350.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "China/glassware cleaning",
        "Cabinet interior organization",
        "Chandelier detailed cleaning",
      ],
      detailedTasks: [
        "✓ Table and chair dusting",
        "✓ Floor vacuum/sweep",
        "✓ Light fixture dusting",
        "✓ Table polishing",
        "✓ Chair detailed cleaning",
        "✓ Baseboards dusting",
        "✓ China cabinet exterior cleaning",
        "✓ Floor detailed cleaning",
        "✓ China/glassware cleaning",
        "✓ Cabinet interior organization",
        "✓ Chandelier detailed cleaning",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  homeOffice: [
    {
      id: "office-standard",
      name: "STANDARD",
      description: "Basic cleaning for work spaces",
      price: 70.0,
      timeEstimate: "15-20 min",
      features: ["Desk surface dusting", "Floor vacuum", "Trash emptying"],
      detailedTasks: ["✓ Desk surface dusting", "✓ Floor vacuum", "✓ Trash emptying"],
      notIncludedTasks: [
        "✗ Electronics dusting",
        "✗ Bookshelf organization",
        "✗ Chair cleaning",
        "✗ Window sill cleaning",
        "✗ Baseboard dusting",
        "✗ Filing cabinet organization",
        "✗ Keyboard and peripheral cleaning",
        "✗ Monitor detailed cleaning",
      ],
      upsellMessage:
        "Boost your productivity with our PREMIUM tier, including detailed electronics dusting and bookshelf organization.",
      guarantee: "7-day",
    },
    {
      id: "office-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for home offices",
      price: 210.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Electronics dusting",
        "Bookshelf organization",
        "Chair cleaning",
        "Window sill cleaning",
        "Baseboard dusting",
      ],
      detailedTasks: [
        "✓ Desk surface dusting",
        "✓ Floor vacuum",
        "✓ Trash emptying",
        "✓ Electronics dusting",
        "✓ Bookshelf organization",
        "✓ Chair cleaning",
        "✓ Window sill cleaning",
        "✓ Baseboard dusting",
      ],
      notIncludedTasks: [
        "✗ Filing cabinet organization",
        "✗ Keyboard and peripheral cleaning",
        "✗ Monitor detailed cleaning",
      ],
      upsellMessage:
        "For a truly professional and organized workspace, our ELITE tier offers comprehensive filing system and keyboard cleaning!",
      guarantee: "30-day",
    },
    {
      id: "office-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for professional offices",
      price: 350.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Filing cabinet organization",
        "Keyboard and peripheral cleaning",
        "Monitor detailed cleaning",
      ],
      detailedTasks: [
        "✓ Desk surface dusting",
        "✓ Floor vacuum",
        "✓ Trash emptying",
        "✓ Electronics dusting",
        "✓ Bookshelf organization",
        "✓ Chair cleaning",
        "✓ Window sill cleaning",
        "✓ Baseboard dusting",
        "✓ Filing cabinet organization",
        "✓ Keyboard and peripheral cleaning",
        "✓ Monitor detailed cleaning",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  laundryRoom: [
    {
      id: "laundry-standard",
      name: "STANDARD",
      description: "Basic cleaning for laundry areas",
      price: 60.0,
      timeEstimate: "15-20 min",
      features: ["Surface dusting", "Floor sweep/vacuum", "Sink cleaning"],
      detailedTasks: ["✓ Surface dusting", "✓ Floor sweep/vacuum", "✓ Sink cleaning"],
      notIncludedTasks: [
        "✗ Washer/dryer exterior cleaning",
        "✗ Countertop detailed cleaning",
        "✗ Floor detailed mopping",
        "✗ Cabinet fronts wiping",
        "✗ Lint trap cleaning",
        "✗ Washer drum cleaning",
        "✗ Dryer vent cleaning",
        "✗ Cabinet interior organization",
      ],
      upsellMessage:
        "For a more hygienic laundry space, our PREMIUM tier includes washer/dryer exterior cleaning and lint trap cleaning.",
      guarantee: "7-day",
    },
    {
      id: "laundry-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for laundry rooms",
      price: 180.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Washer/dryer exterior cleaning",
        "Countertop detailed cleaning",
        "Floor detailed mopping",
        "Cabinet fronts wiping",
        "Lint trap cleaning",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor sweep/vacuum",
        "✓ Sink cleaning",
        "✓ Washer/dryer exterior cleaning",
        "✓ Countertop detailed cleaning",
        "✓ Floor detailed mopping",
        "✓ Cabinet fronts wiping",
        "✓ Lint trap cleaning",
      ],
      notIncludedTasks: ["✗ Washer drum cleaning", "✗ Dryer vent cleaning", "✗ Cabinet interior organization"],
      upsellMessage:
        "For a truly deep clean, our ELITE tier offers washer drum and dryer vent cleaning, plus cabinet interior organization!",
      guarantee: "30-day",
    },
    {
      id: "laundry-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for laundry centers",
      price: 300.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Washer drum cleaning",
        "Dryer vent cleaning",
        "Cabinet interior organization",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor sweep/vacuum",
        "✓ Sink cleaning",
        "✓ Washer/dryer exterior cleaning",
        "✓ Countertop detailed cleaning",
        "✓ Floor detailed mopping",
        "✓ Cabinet fronts wiping",
        "✓ Lint trap cleaning",
        "✓ Washer drum cleaning",
        "✓ Dryer vent cleaning",
        "✓ Cabinet interior organization",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  entryway: [
    {
      id: "entryway-standard",
      name: "STANDARD",
      description: "Basic cleaning for entryways",
      price: 50.0,
      timeEstimate: "15-20 min",
      features: ["Floor sweep/vacuum", "Surface dusting", "Door cleaning"],
      detailedTasks: ["✓ Floor sweep/vacuum", "✓ Surface dusting", "✓ Door cleaning"],
      notIncludedTasks: [
        "✗ Floor detailed mopping",
        "✗ Baseboard dusting",
        "✗ Light fixture dusting",
        "✗ Mirror cleaning",
        "✗ Console table organization",
        "✗ Chandelier detailed cleaning",
      ],
      upsellMessage:
        "Make a grander entrance with our PREMIUM tier, including detailed floor mopping and baseboard dusting.",
      guarantee: "7-day",
    },
    {
      id: "entryway-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for foyers",
      price: 150.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Essential tasks",
        "Floor detailed mopping",
        "Baseboard dusting",
        "Light fixture dusting",
        "Mirror cleaning",
        "Console table organization",
      ],
      detailedTasks: [
        "✓ Floor sweep/vacuum",
        "✓ Surface dusting",
        "✓ Door cleaning",
        "✓ Floor detailed mopping",
        "✓ Baseboard dusting",
        "✓ Light fixture dusting",
        "✓ Mirror cleaning",
        "✓ Console table organization",
      ],
      notIncludedTasks: ["✗ Chandelier detailed cleaning"],
      upsellMessage: "For an immaculate entryway, our ELITE tier offers chandelier cleaning and shoe organization!",
      guarantee: "30-day",
    },
    {
      id: "entryway-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for grand entrances",
      price: 250.0,
      timeEstimate: "90-120 min",
      features: ["Includes Premium tasks", "Chandelier detailed cleaning", "Shoe organization"],
      detailedTasks: [
        "✓ Floor sweep/vacuum",
        "✓ Surface dusting",
        "✓ Door cleaning",
        "✓ Floor detailed mopping",
        "✓ Baseboard dusting",
        "✓ Light fixture dusting",
        "✓ Mirror cleaning",
        "✓ Console table organization",
        "✓ Chandelier detailed cleaning",
        "✓ Shoe organization",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  hallway: [
    {
      id: "hallway-standard",
      name: "STANDARD",
      description: "Basic cleaning for hallways",
      price: 50.0,
      timeEstimate: "15-20 min",
      features: ["Floor vacuum/sweep", "Surface dusting", "Light fixture dusting"],
      detailedTasks: ["✓ Floor vacuum/sweep", "✓ Surface dusting", "✓ Light fixture dusting"],
      notIncludedTasks: [
        "✗ Floor detailed mopping",
        "✗ Baseboard dusting",
        "✗ Wall spot cleaning",
        "✗ Picture frame dusting",
        "✗ Door cleaning",
        "✗ Runner/carpet detailed cleaning",
        "✗ Light fixture detailed cleaning",
      ],
      upsellMessage:
        "For a more pristine hallway, our PREMIUM tier includes detailed floor mopping and baseboard dusting.",
      guarantee: "7-day",
    },
    {
      id: "hallway-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for corridors",
      price: 150.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Floor detailed mopping",
        "Baseboard dusting",
        "Wall spot cleaning",
        "Picture frame dusting",
        "Door cleaning",
      ],
      detailedTasks: [
        "✓ Floor vacuum/sweep",
        "✓ Surface dusting",
        "✓ Light fixture dusting",
        "✓ Floor detailed mopping",
        "✓ Baseboard dusting",
        "✓ Wall spot cleaning",
        "✓ Picture frame dusting",
        "✓ Door cleaning",
      ],
      notIncludedTasks: ["✗ Runner/carpet deep cleaning", "✗ Light fixture detailed cleaning"],
      upsellMessage:
        "For a truly spotless corridor, our ELITE tier offers deep cleaning of runners/carpets and detailed light fixture cleaning!",
      guarantee: "30-day",
    },
    {
      id: "hallway-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for gallery hallways",
      price: 250.0,
      timeEstimate: "90-120 min",
      features: ["Includes Premium tasks", "Runner/carpet deep cleaning", "Light fixture detailed cleaning"],
      detailedTasks: [
        "✓ Floor vacuum/sweep",
        "✓ Surface dusting",
        "✓ Light fixture dusting",
        "✓ Floor detailed mopping",
        "✓ Baseboard dusting",
        "✓ Wall spot cleaning",
        "✓ Picture frame dusting",
        "✓ Door cleaning",
        "✓ Runner/carpet deep cleaning",
        "✓ Light fixture detailed cleaning",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  stairs: [
    {
      id: "stairs-standard",
      name: "STANDARD",
      description: "Basic cleaning for staircases",
      price: 60.0,
      timeEstimate: "15-20 min",
      features: ["Step vacuum/sweep", "Handrail dusting", "Visible surface dusting"],
      detailedTasks: ["✓ Step vacuum/sweep", "✓ Handrail dusting", "✓ Visible surface dusting"],
      notIncludedTasks: [
        "✗ Step detailed cleaning",
        "✗ Handrail detailed cleaning",
        "✗ Baseboard dusting",
        "✗ Spindle dusting",
        "✗ Wall spot cleaning",
        "✗ Carpet deep cleaning",
        "✗ Spindle detailed cleaning",
        "✗ Stair runner detailed cleaning",
      ],
      upsellMessage:
        "For a more thorough staircase clean, our PREMIUM tier includes detailed step and handrail cleaning.",
      guarantee: "7-day",
    },
    {
      id: "stairs-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for stairways",
      price: 180.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Step detailed cleaning",
        "Handrail detailed cleaning",
        "Baseboard dusting",
        "Spindle dusting",
        "Wall spot cleaning",
      ],
      detailedTasks: [
        "✓ Step vacuum/sweep",
        "✓ Handrail dusting",
        "✓ Visible surface dusting",
        "✓ Step detailed cleaning",
        "✓ Handrail detailed cleaning",
        "✓ Baseboard dusting",
        "✓ Spindle dusting",
        "✓ Wall spot cleaning",
      ],
      notIncludedTasks: ["✗ Carpet deep cleaning", "✗ Spindle detailed cleaning", "✗ Stair runner detailed cleaning"],
      upsellMessage:
        "For a truly grand staircase, our ELITE tier offers deep carpet cleaning and detailed spindle cleaning!",
      guarantee: "30-day",
    },
    {
      id: "stairs-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for grand staircases",
      price: 300.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Carpet deep cleaning",
        "Spindle detailed cleaning",
        "Stair runner detailed cleaning",
      ],
      detailedTasks: [
        "✓ Step vacuum/sweep",
        "✓ Handrail dusting",
        "✓ Visible surface dusting",
        "✓ Step detailed cleaning",
        "✓ Handrail detailed cleaning",
        "✓ Baseboard dusting",
        "✓ Spindle dusting",
        "✓ Wall spot cleaning",
        "✓ Carpet deep cleaning",
        "✓ Spindle detailed cleaning",
        "✓ Stair runner detailed cleaning",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
  default: [
    {
      id: "default-standard",
      name: "STANDARD",
      description: "Basic cleaning for all spaces",
      price: 50.0,
      timeEstimate: "15-20 min",
      features: ["Surface dusting", "Floor vacuum/sweep", "General tidying"],
      detailedTasks: ["✓ Surface dusting", "✓ Floor vacuum/sweep", "✓ General tidying"],
      notIncludedTasks: [
        "✗ Detailed dusting",
        "✗ Floor detailed cleaning",
        "✗ Baseboard attention",
        "✗ Surface sanitizing",
        "✗ Specialty surface treatment",
        "✗ Detail work on fixtures",
        "✗ Hard-to-reach areas",
      ],
      upsellMessage: "For a more thorough and detailed clean, consider our PREMIUM tier.",
      guarantee: "7-day",
    },
    {
      id: "default-premium",
      name: "PREMIUM",
      description: "Thorough cleaning for all spaces",
      price: 150.0,
      timeEstimate: "45-60 min",
      features: [
        "Includes Standard tasks",
        "Detailed dusting",
        "Floor detailed cleaning",
        "Baseboard attention",
        "Surface sanitizing",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor vacuum/sweep",
        "✓ General tidying",
        "✓ Detailed dusting",
        "✓ Floor detailed cleaning",
        "✓ Baseboard attention",
        "✓ Surface sanitizing",
      ],
      notIncludedTasks: ["✗ Specialty surface treatment", "✗ Detail work on fixtures", "✗ Hard-to-reach areas"],
      upsellMessage:
        "For the most comprehensive clean, our ELITE tier covers every nook and cranny with specialty treatments!",
      guarantee: "30-day",
    },
    {
      id: "default-elite",
      name: "ELITE",
      description: "Comprehensive cleaning for all spaces",
      price: 250.0,
      timeEstimate: "90-120 min",
      features: [
        "Includes Premium tasks",
        "Specialty surface treatment",
        "Detail work on fixtures",
        "Hard-to-reach areas",
      ],
      detailedTasks: [
        "✓ Surface dusting",
        "✓ Floor vacuum/sweep",
        "✓ General tidying",
        "✓ Detailed dusting",
        "✓ Floor detailed cleaning",
        "✓ Baseboard attention",
        "✓ Surface sanitizing",
        "✓ Specialty surface treatment",
        "✓ Detail work on fixtures",
        "✓ Hard-to-reach areas",
      ],
      notIncludedTasks: [],
      guarantee: "1-year",
    },
  ],
}

// Keep all the existing add-ons and reductions data...
export const defaultAddOns: Record<string, RoomAddOn[]> = {
  // ... existing add-ons data remains the same
  bedroom: [
    {
      id: "bed-1",
      name: "Closet full reorganization",
      price: 25.0,
      description: "Complete organization of closet contents",
    },
    {
      id: "bed-2",
      name: "Blind track deep clean",
      price: 15.0,
      description: "Detailed cleaning of window blind tracks",
    },
    { id: "bed-3", name: "Curtain/shade vacuuming", price: 12.0, description: "Dust removal from window treatments" },
    {
      id: "bed-4",
      name: "Wall mark removal (up to 5 spots)",
      price: 10.0,
      description: "Cleaning of wall marks and scuffs",
    },
    {
      id: "bed-5",
      name: "Nightstand drawer organization",
      price: 8.0,
      description: "Organization of nightstand contents",
    },
  ],
  bathroom: [
    {
      id: "bath-1",
      name: "Shower door track deep clean",
      price: 15.0,
      description: "Detailed cleaning of shower door tracks",
    },
    { id: "bath-2", name: "Grout detailed scrubbing", price: 30.0, description: "Deep cleaning of tile grout" },
    {
      id: "bath-3",
      name: "Cabinet interior organization",
      price: 20.0,
      description: "Organization of bathroom cabinet contents",
    },
    { id: "bath-4", name: "Exhaust fan cleaning", price: 12.0, description: "Cleaning of bathroom exhaust fan" },
    { id: "bath-5", name: "Mold/mildew treatment", price: 25.0, description: "Treatment of mold and mildew spots" },
  ],
  kitchen: [
    {
      id: "kit-1",
      name: "Inside refrigerator cleaning",
      price: 30.0,
      description: "Cleaning of refrigerator interior",
    },
    { id: "kit-2", name: "Inside oven cleaning", price: 35.0, description: "Deep cleaning of oven interior" },
    {
      id: "kit-3",
      name: "Cabinet interior organization (per cabinet)",
      price: 15.0,
      description: "Organization of cabinet contents",
    },
    { id: "kit-4", name: "Dishwasher deep clean", price: 20.0, description: "Detailed cleaning of dishwasher" },
    {
      id: "kit-5",
      name: "Small appliance detailed cleaning",
      price: 10.0,
      description: "Cleaning of countertop appliances",
    },
  ],
  livingRoom: [
    {
      id: "liv-1",
      name: "Upholstery vacuuming",
      price: 20.0,
      description: "Detailed vacuuming of furniture upholstery",
    },
    {
      id: "liv-2",
      name: "Entertainment center organization",
      price: 25.0,
      description: "Organization of entertainment center",
    },
    {
      id: "liv-3",
      name: "Ceiling fan detailed cleaning",
      price: 15.0,
      description: "Detailed cleaning of ceiling fan",
    },
    { id: "liv-4", name: "Window treatment dusting", price: 18.0, description: "Dusting of curtains and blinds" },
    { id: "liv-5", name: "Decor item individual cleaning", price: 12.0, description: "Cleaning of decorative items" },
  ],
  diningRoom: [
    { id: "din-1", name: "China cabinet interior cleaning", price: 25.0, description: "Cleaning inside china cabinet" },
    { id: "din-2", name: "Chair upholstery cleaning", price: 20.0, description: "Cleaning of dining chair upholstery" },
    {
      id: "din-3",
      name: "Table leaf cleaning & storage",
      price: 15.0,
      description: "Cleaning and proper storage of table leaves",
    },
    {
      id: "din-4",
      name: "Chandelier detailed cleaning",
      price: 30.0,
      description: "Detailed cleaning of dining room chandelier",
    },
    {
      id: "din-5",
      name: "Silverware polishing",
      price: 25.0,
      description: "Polishing of silverware and serving pieces",
    },
  ],
  homeOffice: [
    {
      id: "off-1",
      name: "Computer peripheral cleaning",
      price: 15.0,
      description: "Cleaning of keyboard, mouse, etc.",
    },
    {
      id: "off-2",
      name: "File organization (per drawer)",
      price: 20.0,
      description: "Organization of file drawer contents",
    },
    { id: "off-3", name: "Bookshelf organization", price: 25.0, description: "Organization of books and materials" },
    { id: "off-4", name: "Cable management", price: 15.0, description: "Organization and securing of cables" },
    { id: "off-5", name: "Desk drawer organization", price: 18.0, description: "Organization of desk drawer contents" },
  ],
  laundryRoom: [
    { id: "lau-1", name: "Washer deep cleaning", price: 25.0, description: "Deep cleaning of washing machine" },
    { id: "lau-2", name: "Dryer vent cleaning", price: 20.0, description: "Cleaning of dryer vent and lint trap" },
    { id: "lau-3", name: "Supply organization", price: 15.0, description: "Organization of laundry supplies" },
    { id: "lau-4", name: "Under appliance cleaning", price: 18.0, description: "Cleaning under washer and dryer" },
    { id: "lau-5", name: "Utility sink deep clean", price: 15.0, description: "Deep cleaning of laundry sink" },
  ],
  entryway: [
    { id: "ent-1", name: "Shoe organization", price: 15.0, description: "Organization of shoes and boots" },
    { id: "ent-2", name: "Coat closet organization", price: 20.0, description: "Organization of coat closet contents" },
    { id: "ent-3", name: "Entry mat deep cleaning", price: 12.0, description: "Deep cleaning of entry mats" },
    {
      id: "ent-4",
      name: "Door hardware polishing",
      price: 10.0,
      description: "Polishing of door handles and hardware",
    },
    { id: "ent-5", name: "Mail/key area organization", price: 15.0, description: "Organization of mail and key area" },
  ],
  hallway: [
    {
      id: "hal-1",
      name: "Runner/carpet deep cleaning",
      price: 20.0,
      description: "Deep cleaning of hallway carpet or runner",
    },
    {
      id: "hal-2",
      name: "Picture frame detailed cleaning",
      price: 15.0,
      description: "Detailed cleaning of picture frames",
    },
    {
      id: "hal-3",
      name: "Linen closet organization",
      price: 25.0,
      description: "Organization of linen closet contents",
    },
    {
      id: "hal-4",
      name: "Light fixture detailed cleaning",
      price: 18.0,
      description: "Detailed cleaning of hallway light fixtures",
    },
    { id: "hal-5", name: "Wall sconce cleaning", price: 12.0, description: "Cleaning of wall sconces" },
  ],
  stairs: [
    { id: "sta-1", name: "Carpet deep cleaning", price: 25.0, description: "Deep cleaning of stair carpet" },
    {
      id: "sta-2",
      name: "Banister detailed cleaning",
      price: 20.0,
      description: "Detailed cleaning of banister and railings",
    },
    { id: "sta-3", name: "Stair riser cleaning", price: 15.0, description: "Cleaning of stair risers" },
    {
      id: "sta-4",
      name: "Under-stair cleaning (if accessible)",
      price: 30.0,
      description: "Cleaning of accessible under-stair areas",
    },
    {
      id: "sta-5",
      name: "Stair runner detailed cleaning",
      price: 22.0,
      description: "Detailed cleaning of stair runner",
    },
  ],
  default: [
    {
      id: "def-1",
      name: "Detailed dusting of all surfaces",
      price: 15.0,
      description: "Comprehensive dusting of all surfaces",
    },
    { id: "def-2", name: "Wall spot cleaning", price: 12.0, description: "Cleaning of wall spots and marks" },
    {
      id: "def-3",
      name: "Ceiling corner cobweb removal",
      price: 8.0,
      description: "Removal of cobwebs from ceiling corners",
    },
    { id: "def-4", name: "Light fixture cleaning", price: 10.0, description: "Cleaning of light fixtures" },
    { id: "def-5", name: "Door/doorframe cleaning", price: 10.0, description: "Cleaning of doors and doorframes" },
  ],
}

export const defaultReductions: Record<string, RoomReduction[]> = {
  bedroom: [
    { id: "bed-r1", name: "Skip mirror cleaning", discount: 5.0, description: "Mirrors will not be cleaned" },
    {
      id: "bed-r2",
      name: "Limit to 2 furniture pieces",
      discount: 8.0,
      description: "Only 2 furniture pieces will be cleaned",
    },
    {
      id: "bed-r3",
      name: "No under-bed cleaning",
      discount: 10.0,
      description: "Area under the bed will not be cleaned",
    },
    {
      id: "bed-r4",
      name: "Basic surface dusting only",
      discount: 7.0,
      description: "Only basic dusting will be performed",
    },
  ],
  bathroom: [
    { id: "bath-r1", name: "Skip shower/tub cleaning", discount: 15.0, description: "Shower/tub will not be cleaned" },
    {
      id: "bath-r2",
      name: "Basic toilet cleaning only",
      discount: 8.0,
      description: "Only basic toilet cleaning will be performed",
    },
    { id: "bath-r3", name: "Skip floor mopping", discount: 10.0, description: "Floor will not be mopped" },
    { id: "bath-r4", name: "No cabinet cleaning", discount: 5.0, description: "Cabinets will not be cleaned" },
  ],
  kitchen: [
    {
      id: "kit-r1",
      name: "Skip appliance exteriors",
      discount: 12.0,
      description: "Appliance exteriors will not be cleaned",
    },
    {
      id: "kit-r2",
      name: "Basic countertop cleaning only",
      discount: 10.0,
      description: "Only basic countertop cleaning will be performed",
    },
    { id: "kit-r3", name: "No floor mopping", discount: 15.0, description: "Floor will not be mopped" },
    {
      id: "kit-r4",
      name: "Skip sink deep cleaning",
      discount: 8.0,
      description: "Sink will receive only basic cleaning",
    },
  ],
  livingRoom: [
    {
      id: "liv-r1",
      name: "Skip under furniture",
      discount: 12.0,
      description: "Areas under furniture will not be cleaned",
    },
    {
      id: "liv-r2",
      name: "Basic vacuum only (no edges)",
      discount: 10.0,
      description: "Only basic vacuuming will be performed",
    },
    { id: "liv-r3", name: "No electronics dusting", discount: 8.0, description: "Electronics will not be dusted" },
    {
      id: "liv-r4",
      name: "Skip decor item cleaning",
      discount: 7.0,
      description: "Decorative items will not be cleaned",
    },
  ],
  diningRoom: [
    { id: "din-r1", name: "Skip chair cleaning", discount: 10.0, description: "Chairs will not be cleaned" },
    {
      id: "din-r2",
      name: "Basic table cleaning only",
      discount: 8.0,
      description: "Only basic table cleaning will be performed",
    },
    {
      id: "din-r3",
      name: "No china cabinet cleaning",
      discount: 12.0,
      description: "China cabinet will not be cleaned",
    },
    {
      id: "din-r4",
      name: "Skip light fixture dusting",
      discount: 7.0,
      description: "Light fixtures will not be dusted",
    },
  ],
  homeOffice: [
    { id: "off-r1", name: "Skip electronics dusting", discount: 10.0, description: "Electronics will not be dusted" },
    { id: "off-r2", name: "No bookshelf cleaning", discount: 12.0, description: "Bookshelves will not be cleaned" },
    {
      id: "off-r3",
      name: "Basic desk cleaning only",
      discount: 8.0,
      description: "Only basic desk cleaning will be performed",
    },
    { id: "off-r4", name: "Skip floor edges", discount: 7.0, description: "Floor edges will not be cleaned" },
  ],
  laundryRoom: [
    {
      id: "lau-r1",
      name: "Skip appliance exteriors",
      discount: 10.0,
      description: "Appliance exteriors will not be cleaned",
    },
    { id: "lau-r2", name: "No sink cleaning", discount: 8.0, description: "Sink will not be cleaned" },
    {
      id: "lau-r3",
      name: "Basic floor cleaning only",
      discount: 7.0,
      description: "Only basic floor cleaning will be performed",
    },
    { id: "lau-r4", name: "Skip cabinet fronts", discount: 6.0, description: "Cabinet fronts will not be cleaned" },
  ],
  entryway: [
    {
      id: "ent-r1",
      name: "Basic floor cleaning only",
      discount: 8.0,
      description: "Only basic floor cleaning will be performed",
    },
    { id: "ent-r2", name: "Skip door cleaning", discount: 6.0, description: "Door will not be cleaned" },
    {
      id: "ent-r3",
      name: "No console table cleaning",
      discount: 7.0,
      description: "Console table will not be cleaned",
    },
    {
      id: "ent-r4",
      name: "Skip mirror/artwork cleaning",
      discount: 5.0,
      description: "Mirrors and artwork will not be cleaned",
    },
  ],
  hallway: [
    {
      id: "hal-r1",
      name: "Basic floor cleaning only",
      discount: 8.0,
      description: "Only basic floor cleaning will be performed",
    },
    { id: "hal-r2", name: "Skip wall cleaning", discount: 6.0, description: "Walls will not be cleaned" },
    { id: "hal-r3", name: "No picture frame dusting", discount: 5.0, description: "Picture frames will not be dusted" },
    { id: "hal-r4", name: "Skip baseboard cleaning", discount: 7.0, description: "Baseboards will not be cleaned" },
  ],
  stairs: [
    {
      id: "sta-r1",
      name: "Basic step cleaning only",
      discount: 10.0,
      description: "Only basic step cleaning will be performed",
    },
    { id: "sta-r2", name: "Skip handrail cleaning", discount: 8.0, description: "Handrail will not be cleaned" },
    { id: "sta-r3", name: "No spindle dusting", discount: 7.0, description: "Spindles will not be dusted" },
    { id: "sta-r4", name: "Skip stair edges", discount: 6.0, description: "Stair edges will not be cleaned" },
  ],
  default: [
    {
      id: "def-r1",
      name: "Skip detailed dusting",
      discount: 10.0,
      description: "Detailed dusting will not be performed",
    },
    {
      id: "def-r2",
      name: "Basic floor cleaning only",
      discount: 12.0,
      description: "Only basic floor cleaning will be performed",
    },
    { id: "def-r3", name: "No baseboard cleaning", discount: 8.0, description: "Baseboards will not be cleaned" },
    {
      id: "def-r4",
      name: "Skip hard-to-reach areas",
      discount: 10.0,
      description: "Hard-to-reach areas will not be cleaned",
    },
  ],
}

// Helper function to get tiers for a specific room type
export function getRoomTiers(roomType: string): RoomTier[] {
  return defaultTiers[roomType] || defaultTiers.default
}

// Helper function to get add-ons for a specific room type
export function getRoomAddOns(roomType: string): RoomAddOn[] {
  return defaultAddOns[roomType] || defaultAddOns.default
}

// Helper function to get reductions for a specific room type
export function getRoomReductions(roomType: string): RoomReduction[] {
  return defaultReductions[roomType] || defaultReductions.default
}

// Room type to professional image mapping
export const roomImages: Record<string, string> = {
  bedroom: "/images/bedroom-professional.png",
  bathroom: "/images/bathroom-professional.png",
  kitchen: "/images/kitchen-professional.png",
  livingRoom: "/images/living-room-professional.png",
  diningRoom: "/images/dining-room-professional.png",
  homeOffice: "/images/home-office-professional.png",
  laundryRoom: "/images/laundry-room-professional.png",
  entryway: "/images/entryway-professional.png",
  hallway: "/images/hallway-professional.png",
  stairs: "/images/stairs-professional.png",
  other: "/images/bedroom-professional.png", // fallback
}

// Room type to icon mapping (keeping as fallback)
export const roomIcons: Record<string, string> = {
  bedroom: "🛏️",
  bathroom: "🚿",
  kitchen: "🍳",
  livingRoom: "🛋️",
  diningRoom: "🍽️",
  homeOffice: "💻",
  laundryRoom: "🧺",
  entryway: "🚪",
  hallway: "🚶",
  stairs: "🪜",
  other: "➕",
}

// Room type to display name mapping
export const roomDisplayNames: Record<string, string> = {
  bedroom: "Bedroom",
  bathroom: "Bathroom",
  kitchen: "Kitchen",
  livingRoom: "Living Room",
  diningRoom: "Dining Room",
  homeOffice: "Home Office",
  laundryRoom: "Laundry Room",
  entryway: "Entryway",
  hallway: "Hallway",
  stairs: "Stairs",
  other: "Other Space",
}
