export interface ServiceFeature {
  name: string
  description: string
  quickClean: boolean | "partial"
  deepClean: boolean | "partial"
  premium: boolean | "partial"
  tooltip?: string
}

// Define service features for each room type
const serviceFeaturesData: Record<string, ServiceFeature[]> = {
  bedroom: [
    {
      name: "Surface Dusting",
      description: "Dusting of all accessible surfaces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Vacuuming/Sweeping",
      description: "Vacuuming or sweeping of main floor areas.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Mirror/Glass Cleaning",
      description: "Streak-free cleaning of mirrors and glass surfaces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Under-Bed Cleaning",
      description: "Cleaning of areas under the bed.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Baseboard Cleaning",
      description: "Wiping down and dusting of baseboards.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Closet Organization",
      description: "Tidying and organizing visible items in closets.",
      quickClean: false,
      deepClean: "partial",
      premium: true,
      tooltip: "Partial includes visible items, Premium includes deep organization.",
    },
    {
      name: "Mattress Steaming/Sanitization",
      description: "Steaming and sanitizing of mattress surfaces.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Light Fixture Detailed Cleaning",
      description: "Disassembling and deep cleaning of light fixtures.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Wall Spot Cleaning",
      description: "Spot cleaning of visible marks on walls.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  bathroom: [
    {
      name: "Sink & Counter Cleaning",
      description: "Cleaning and sanitizing of sink and countertop areas.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Toilet Cleaning",
      description: "Cleaning and sanitizing of toilet bowl and exterior.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Shower/Tub Cleaning",
      description: "Scrubbing and sanitizing of shower and tub.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Mopping",
      description: "Detailed mopping of bathroom floors.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Grout Cleaning",
      description: "Detailed scrubbing and treatment of tile grout.",
      quickClean: false,
      deepClean: "partial",
      premium: true,
      tooltip: "Partial includes basic grout cleaning, Premium includes deep grout restoration.",
    },
    {
      name: "Cabinet Exterior Cleaning",
      description: "Wiping down and polishing of cabinet fronts.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Cabinet Interior Organization",
      description: "Organization of cabinet contents.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Exhaust Fan Cleaning",
      description: "Cleaning of bathroom exhaust fan.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Fixture Polishing",
      description: "Polishing of faucets and other metal fixtures.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  kitchen: [
    {
      name: "Countertop Cleaning",
      description: "Cleaning and sanitizing of all countertop surfaces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Sink & Faucet Cleaning",
      description: "Scrubbing and sanitizing of sink and faucet.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Stovetop & Microwave Cleaning",
      description: "Wipe-down of stovetop and interior/exterior of microwave.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Appliance Exterior Cleaning",
      description: "Wiping down and polishing of all appliance exteriors.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Oven Interior Cleaning",
      description: "Deep cleaning of oven interior.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Refrigerator Interior Cleaning",
      description: "Cleaning and organizing of refrigerator interior.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Cabinet Fronts Cleaning",
      description: "Wiping down and polishing of cabinet fronts.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Cleaning",
      description: "Detailed sweeping and mopping of kitchen floor.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Pantry Organization",
      description: "Tidying and organizing pantry shelves.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  livingRoom: [
    {
      name: "Surface Dusting",
      description: "Dusting of all accessible surfaces (tables, shelves, etc.).",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Vacuuming",
      description: "Vacuuming of main walkways and open floor areas.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Coffee/End Table Cleaning",
      description: "Wiping down and tidying of coffee and end tables.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Furniture Vacuuming",
      description: "Vacuuming of upholstered furniture (sofas, chairs).",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Under Furniture Cleaning",
      description: "Cleaning of accessible areas under furniture.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Baseboard Dusting",
      description: "Dusting of all baseboards.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Electronics Dusting",
      description: "Dusting of TVs, sound systems, and other electronics.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Upholstery Spot Treatment",
      description: "Treatment of visible spots on upholstered furniture.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Ceiling Fan Detailed Cleaning",
      description: "Disassembling and deep cleaning of ceiling fan blades.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  diningRoom: [
    {
      name: "Table & Chair Dusting",
      description: "Dusting of dining table and chairs.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Vacuum/Sweep",
      description: "Vacuuming or sweeping of dining area floor.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Light Fixture Dusting",
      description: "Dusting of overhead light fixtures.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Table Polishing",
      description: "Polishing of dining table surface.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Chair Detailed Cleaning",
      description: "Detailed cleaning of chair frames and legs.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "China Cabinet Exterior Cleaning",
      description: "Wiping down and polishing of china cabinet exterior.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "China/Glassware Cleaning",
      description: "Hand washing and organizing of fine china and glassware.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Chandelier Detailed Cleaning",
      description: "Disassembling and detailed cleaning of chandeliers.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  homeOffice: [
    {
      name: "Desk Surface Dusting",
      description: "Dusting and wiping of desk surfaces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Vacuuming",
      description: "Vacuuming of office floor areas.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Trash Emptying",
      description: "Emptying trash bins and replacing liners.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Electronics Dusting",
      description: "Dusting of computer, monitor, and peripherals.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Bookshelf Organization",
      description: "Tidying and organizing books and items on shelves.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Keyboard & Peripheral Cleaning",
      description: "Detailed cleaning and sanitizing of keyboard and mouse.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Cable Management",
      description: "Organizing and securing visible cables.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Filing Cabinet Organization",
      description: "Organizing files and folders in cabinets.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  laundryRoom: [
    {
      name: "Surface Dusting",
      description: "Dusting and wiping of all accessible surfaces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Floor Sweep/Vacuum",
      description: "Sweeping or vacuuming of laundry room floor.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Sink Cleaning",
      description: "Cleaning and wiping of laundry sink.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Washer/Dryer Exterior Cleaning",
      description: "Wiping down and polishing of washer and dryer exteriors.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Lint Trap Cleaning",
      description: "Cleaning of dryer lint trap and surrounding area.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Washer Drum Cleaning",
      description: "Deep cleaning and sanitizing of washer drum.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Dryer Vent Cleaning",
      description: "Disassembling and cleaning of dryer vent.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  entryway: [
    {
      name: "Floor Sweep/Vacuum",
      description: "Sweeping or vacuuming of entryway floor.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Surface Dusting",
      description: "Dusting of console tables, benches, etc.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Door & Handle Cleaning",
      description: "Wiping down entry door and cleaning handles.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Baseboard Dusting",
      description: "Dusting of entryway baseboards.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Mirror Cleaning",
      description: "Streak-free cleaning of entryway mirrors.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Shoe Organization",
      description: "Organizing shoes and boots.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
    {
      name: "Coat Closet Organization",
      description: "Organizing contents of the coat closet.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  hallway: [
    {
      name: "Floor Vacuum/Sweep",
      description: "Vacuuming or sweeping of hallway floor.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Surface Dusting",
      description: "Dusting of any visible surfaces (console tables, shelves).",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Light Fixture Dusting",
      description: "Dusting of overhead light fixtures and sconces.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Baseboard Dusting",
      description: "Dusting and wiping of hallway baseboards.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Wall Spot Cleaning",
      description: "Spot cleaning of visible marks on walls.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Picture Frame Dusting",
      description: "Dusting of all picture frames.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Runner/Carpet Deep Cleaning",
      description: "Deep cleaning of hallway runners or carpets.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
  stairs: [
    {
      name: "Step Vacuum/Sweep",
      description: "Vacuuming or sweeping of stair steps.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Handrail Dusting",
      description: "Dusting and wiping of handrails.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Visible Surface Dusting",
      description: "Dusting of any visible surfaces on the staircase.",
      quickClean: true,
      deepClean: true,
      premium: true,
    },
    {
      name: "Step Detailed Cleaning",
      description: "Detailed cleaning of steps, including edges and corners.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Baseboard Dusting",
      description: "Dusting of baseboards along the staircase.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Spindle Dusting",
      description: "Dusting of all staircase spindles.",
      quickClean: false,
      deepClean: true,
      premium: true,
    },
    {
      name: "Carpet Deep Cleaning",
      description: "Deep cleaning of stair carpet.",
      quickClean: false,
      deepClean: false,
      premium: true,
    },
  ],
}

export function getServiceFeatures(roomType: string): ServiceFeature[] {
  return serviceFeaturesData[roomType] || []
}
